### ISSUE TITLE
Data Preprocessing

### ISSUE THREAD

**Issue by malhar2460** [MSTC-DA-IICT/Hacktoberfest24-Mushroom-Edibility-Prediction-ML#1]
## Objective
Convert the categorical features in the dataset into numerical representations for the classification task of determining whether the ***'mushroom'*** is ***'poisonous'*** or ***'edible'***.

## Tasks
- Improve the data preprocessing workflow.
- Data Cleaning & Transformation.
- Feature Engineering
- Encoding of categorial data, and also provide reason behind use of any particular encoding technique.

### The code should be well commented explaining the reason behind steps where necessary.

**Comment by Abhicoder03** [comment]
@malhar2460  Hey I find this issue interesting. I want to work on this. Will you please assign this to me.

**Comment by Monson2002** [comment]
Hi @malhar2460  can you assign this issue to me, I have completed this on my local machine

**Comment by frectrium** [comment]
Hey @malhar2460, I've the solved the issue, and it's working fine on my local machine. I'm raising a PR, can you please look into it and merge it if it is correct?

**Comment by venilv912** [comment]
@Monson2002 and @frectrium , can You both describe what steps did you take for Data Preprocessing, and how are they useful?

**Comment by Monson2002** [comment]
@venilv912 First I did a little exploration on the given data , using df.info and df.columns. The column 'poisonous' has two values: 'p' (poisonous) and 'e' (edible). This is categorical in nature. I chose to change the label as :
p -> 1
e -> 0
There are two main reasons for this preprocessing:
1. Its always more preferable to have numerical values instead of categorical for ease in analysis
2. The column header is named 'poisonous' which implies the value should tell whether its poisonous or not ie. It should be a boolean, so I chose 1 and 0

**Comment by malhar2460** [comment]
@eric157, can you explain the steps you took for pre processing the data and how these steps will help further?

**Comment by eric157** [comment]
Hey @malhar2460  , for preprocessing, 
I started by filling missing values in the stalk-root column with 'unknown' to avoid losing data. 
Then, I created new interaction features like cap-shape_surface and cap-color_odor to capture deeper relationships between mushroom traits.
I applied label encoding for ordered columns and one-hot encoding for the rest to convert categorical data into numerical form. 
Finally, I mapped the poisonous column to 0 (edible) and 1 (poisonous) for easier classification. These steps make the data clean and help the model understand it better.
